# Generated by Django 5.0.6 on 2024-06-11 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=500)),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('class_user', models.CharField(max_length=2)),
                ('count_checkpoint', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
                ('users', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('checkpoint', models.ManyToManyField(to='game.task')),
            ],
        ),
    ]
