# Generated by Django 5.0.6 on 2024-06-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullname',
            old_name='name',
            new_name='FIO_user',
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='surname',
        ),
    ]
