# Generated by Django 5.0.6 on 2024-06-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_fullname_fio_user_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='task',
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_use',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fio', to=settings.AUTH_USER_MODEL),
        ),
    ]
