# Generated by Django 5.0.6 on 2024-06-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_progress_checkpoint_remove_progress_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='progress_use',
            new_name='progress_user',
        ),
    ]
